### ISSUE TITLE
linkable video pages

### ISSUE THREAD

**Issue by ls-daniil** [vace117/dash#2]
as a nerfy internet user, 
i would like to be able to receive a hyperlink from other nerfs, 
wheupon i paste said hyperlink from within my clipboard and into
the address bar of google chrome
or firefox
or ms edgelord 
that would take me to the loginpage 
and then to the video
provided that i logged in ok
qed

**Comment by vace117** [comment]
Feature has been implemented.

![linkable_video-pages](https://user-images.githubusercontent.com/3578497/90332251-f3f5c680-df80-11ea-841c-aa6851e7d306.png)
